// Copyright (c) 2026 Maptek Pty Ltd
// Licensed under the MIT License
#pragma once
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#define COBALT_RENDERER_ADDED_DEFINE_NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#define COBALT_RENDERER_ADDED_DEFINE_WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>
#ifdef COBALT_RENDERER_ADDED_DEFINE_NOMINMAX
#undef NOMINMAX
#undef COBALT_RENDERER_ADDED_DEFINE_NOMINMAX
#endif
#ifdef COBALT_RENDERER_ADDED_DEFINE_WIN32_LEAN_AND_MEAN
#undef WIN32_LEAN_AND_MEAN
#undef COBALT_RENDERER_ADDED_DEFINE_WIN32_LEAN_AND_MEAN
#endif
#endif
